version: "2"
services:
  rethonk:
    image: rethinkdb
    volumes:
      - .:/data
  redis:
    image: redis
  lavalink:
    image: fredboat/lavalink
    volumes:
      - lavalink.yml:/opt/Lavalink/application.yml
  mantaro:
    depends_on:
      - "rethonk"
      - "redis"
      - "lavalink"
    image: mantaro/mantaro
    volumes:
      - ./config-compose.json:/mantaro/config.json
  prometheus:
    depends_on:
      - "mantaro"
    image: prom/prometheus
    volumes:
      - ./prometheus:/prometheus-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
